from django.urls import path
from Training_management_app.EditResultView import EditResultView
from . import managementviews, trainerviews, studentviews, views

urlpatterns = [
    path("", views.login_page, name='login_page'),
    path("get_attendance", views.get_attendance, name='get_attendance'),
    path("firebase-messaging-sw.js", views.showFirebaseJS, name='showFirebaseJS'),
    path("doLogin/", views.doLogin, name='user_login'),
    path("logout_user/", views.logout_user, name='user_logout'),
    path("admin/home/", managementviews.admin_home, name='admin_home'),
    path("trainer/add", managementviews.add_trainer, name='add_trainer'),
    path("course/add", managementviews.add_course, name='add_course'),
    path("send_student_notification/", managementviews.send_student_notification,
         name='send_student_notification'),
    path("send_trainer_notification/", managementviews.send_trainer_notification,
         name='send_trainer_notification'),
    path("add_session/", managementviews.add_session, name='add_session'),
    path("admin_notify_student", managementviews.admin_notify_student,
         name='admin_notify_student'),
    path("admin_notify_trainer", managementviews.admin_notify_trainer,
         name='admin_notify_trainer'),
    path("admin_view_profile", managementviews.admin_view_profile,
         name='admin_view_profile'),
    path("check_email_availability", managementviews.check_email_availability,
         name="check_email_availability"),
    path("session/manage/", managementviews.manage_session, name='manage_session'),
    path("session/edit/<int:session_id>",
         managementviews.edit_session, name='edit_session'),
    path("student/view/feedback/", managementviews.student_feedback_message,
         name="student_feedback_message",),
    path("trainer/view/feedback/", managementviews.trainer_feedback_message,
         name="trainer_feedback_message",),
    path("student/view/leave/", managementviews.view_student_leave,
         name="view_student_leave",),
    path("trainer/view/leave/", managementviews.view_trainer_leave, name="view_trainer_leave",),
    path("attendance/view/", managementviews.admin_view_attendance,
         name="admin_view_attendance",),
    path("attendance/fetch/", managementviews.get_admin_attendance,
         name='get_admin_attendance'),
    path("student/add/", managementviews.add_student, name='add_student'),
    path("subject/add/", managementviews.add_subject, name='add_subject'),
    path("trainer/manage/", managementviews.manage_trainer, name='manage_trainer'),
    path("student/manage/", managementviews.manage_student, name='manage_student'),
    path("course/manage/", managementviews.manage_course, name='manage_course'),
    path("subject/manage/", managementviews.manage_subject, name='manage_subject'),
    path("trainer/edit/<int:trainer_id>", managementviews.edit_trainer, name='edit_trainer'),
    path("trainer/delete/<int:trainer_id>",
         managementviews.delete_trainer, name='delete_trainer'),

    path("course/delete/<int:course_id>",
         managementviews.delete_course, name='delete_course'),

    path("subject/delete/<int:subject_id>",
         managementviews.delete_subject, name='delete_subject'),

    path("session/delete/<int:session_id>",
         managementviews.delete_session, name='delete_session'),

    path("student/delete/<int:student_id>",
         managementviews.delete_student, name='delete_student'),
    path("student/edit/<int:student_id>",
         managementviews.edit_student, name='edit_student'),
    path("course/edit/<int:course_id>",
         managementviews.edit_course, name='edit_course'),
    path("subject/edit/<int:subject_id>",
         managementviews.edit_subject, name='edit_subject'),

    # Staff
    path("trainer/home/", trainerviews.trainer_home, name='trainer_home'),
    path("trainer/apply/leave/", trainerviews.trainer_apply_leave,
         name='trainer_apply_leave'),
    path("trainer/feedback/", trainerviews.trainer_feedback, name='trainer_feedback'),
    path("trainer/view/profile/", trainerviews.trainer_view_profile,
         name='trainer_view_profile'),
    path("trainer/attendance/take/", trainerviews.trainer_take_attendance,
         name='trainer_take_attendance'),
    path("trainer/attendance/update/", trainerviews.trainer_update_attendance,
         name='trainer_update_attendance'),
    path("trainer/get_students/", trainerviews.get_students, name='get_students'),
    path("trainer/attendance/fetch/", trainerviews.get_student_attendance,
         name='get_student_attendance'),
    path("trainer/attendance/save/",
         trainerviews.save_attendance, name='save_attendance'),
    path("trainer/attendance/update/",
         trainerviews.update_attendance, name='update_attendance'),
    path("trainer/fcmtoken/", trainerviews.trainer_fcmtoken, name='trainer_fcmtoken'),
    path("trainer/view/notification/", trainerviews.trainer_view_notification,
         name="trainer_view_notification"),
    path("trainer/result/add/", trainerviews.trainer_add_result, name='trainer_add_result'),
    path("trainer/result/edit/", EditResultView.as_view(),
         name='edit_student_result'),
    path('trainer/result/fetch/', trainerviews.fetch_student_result,
         name='fetch_student_result'),



    # Student
    path("student/home/", studentviews.student_home, name='student_home'),
    path("student/view/attendance/", studentviews.student_view_attendance,
         name='student_view_attendance'),
    path("student/apply/leave/", studentviews.student_apply_leave,
         name='student_apply_leave'),
    path("student/feedback/", studentviews.student_feedback,
         name='student_feedback'),
    path("student/view/profile/", studentviews.student_view_profile,
         name='student_view_profile'),
    path("student/fcmtoken/", studentviews.student_fcmtoken,
         name='student_fcmtoken'),
    path("student/view/notification/", studentviews.student_view_notification,
         name="student_view_notification"),
    path('student/view/result/', studentviews.student_view_result,
         name='student_view_result'),

]
